/*
* TP3 Projet Super Puissance 4
TDC1 
Chakir EL HADDAOUI et Maeldane MAINGUY
23 Octobre 2020
 */
package superpuissance4_console;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author maeldicomputer
 */
public class fenetreDejeu extends javax.swing.JFrame {

    Joueur Listejoueurs[] = new Joueur[2];
    Joueur JoueurCourant;
    Grille grilleDeJeu = new Grille();

    /**
     * Creates new form fenetreDejeu
     */
    public fenetreDejeu() {
        initComponents();
        panneau_info_joueur.setVisible(false);
        panneau_info_partie.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleDeJeu.Cellules[i][j]);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Cellule c = cellGraph.celluleAssociee;
                        if (c.jetonCourant == null) {
                            return;
                        }

                        if (c.jetonCourant.Couleur.equals(JoueurCourant.Couleur)) {
                            textemessage.setText("le joueur " + JoueurCourant.Nom + " récupère un de ses jetons ");
                            Jeton jrecup = c.recupererJeton();
                            JoueurCourant.ajouterJeton(jrecup);
                            joueurSuivant();
                        } else {
                            if (JoueurCourant.nombreDesintegrateurs > 0) {

                                textemessage.setText("le joueur " + JoueurCourant.Nom + " veut désintégrer un jetons ");
                                c.supprimerJeton();
                                JoueurCourant.utiliserDesintegrateur();
                                joueurSuivant();
                            } else {
                                return;
                            }

                        }
                        grilleDeJeu.tasserGrille();
                        
                        panneau_grille.repaint();

                        lbl_j1_desint.setText(Listejoueurs[0].nombreDesintegrateurs + "");
                        lbl_j2_desint.setText(Listejoueurs[1].nombreDesintegrateurs + "");

                        boolean vict_j1 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[0]);
                        boolean vict_j2 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[1]);

                        if (vict_j1 && !vict_j2) {
                            textemessage.setText(" Victoire de  " + Listejoueurs[0].Nom);
                        }
                        if (vict_j2 && !vict_j1) {
                            textemessage.setText(" Victoire de  " + Listejoueurs[1].Nom);
                        }

                        if (vict_j1 && !vict_j2) {
                            if (JoueurCourant == Listejoueurs[0]) {
                                textemessage.setText(" Victoire de  " + Listejoueurs[1].Nom + "(faute de jeu de l'autre joueur)");
                            } else {
                                textemessage.setText(" Victoire de  " + Listejoueurs[0].Nom + "(faute de jeu de l'autre joueur)");
                            }

                        }
                    }
                });

                panneau_grille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panneau_grille = new javax.swing.JPanel();
        panneau_info_joueur = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        textemessage = new javax.swing.JTextArea();
        panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom_joueur2 = new javax.swing.JTextField();
        nom_joueur1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_info_partie = new javax.swing.JPanel();
        lbl_j1_desint = new javax.swing.JLabel();
        lbl_j1_couleur = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_j2_desint = new javax.swing.JLabel();
        lbl_j2_nom = new javax.swing.JLabel();
        lbl_j2_couleur = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_j1_nom1 = new javax.swing.JLabel();
        btn_col_6 = new javax.swing.JButton();
        btn_col_0 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();

        jLabel2.setText("Nom Joueur 1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 672, 576));

        panneau_info_joueur.setBackground(new java.awt.Color(204, 255, 204));
        panneau_info_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Infos Jeu ");
        panneau_info_joueur.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel11.setForeground(new java.awt.Color(204, 153, 0));
        jLabel11.setText("Joueur Courant : ");
        panneau_info_joueur.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbl_jcourant.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_jcourant.setForeground(new java.awt.Color(204, 153, 0));
        lbl_jcourant.setText("nomJoueur");
        panneau_info_joueur.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        textemessage.setColumns(20);
        textemessage.setRows(5);
        message.setViewportView(textemessage);

        panneau_info_joueur.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        getContentPane().add(panneau_info_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 290, 170));

        panneau_creation_partie.setBackground(new java.awt.Color(204, 255, 204));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Nom Joueur 2 : ");
        panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Nom Joueur 1 : ");
        panneau_creation_partie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        nom_joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur2ActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, 40));
        panneau_creation_partie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 16, 140, 40));

        btn_start.setBackground(new java.awt.Color(0, 255, 0));
        btn_start.setText("Démarrer Partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 290, 140));

        panneau_info_partie.setBackground(new java.awt.Color(204, 255, 204));
        panneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_j1_desint.setForeground(new java.awt.Color(0, 0, 153));
        lbl_j1_desint.setText("nbdesintjoueur1 ");
        panneau_info_partie.add(lbl_j1_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        lbl_j1_couleur.setForeground(new java.awt.Color(0, 0, 153));
        lbl_j1_couleur.setText("couleurjoueur1");
        panneau_info_partie.add(lbl_j1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Joueur 1 : ");
        panneau_info_partie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Couleur : ");
        panneau_info_partie.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Desintegrateurs : ");
        panneau_info_partie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        panneau_info_partie.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 20));

        lbl_j2_desint.setForeground(new java.awt.Color(0, 102, 0));
        lbl_j2_desint.setText("nbdesintjoueur2 ");
        panneau_info_partie.add(lbl_j2_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        lbl_j2_nom.setForeground(new java.awt.Color(0, 102, 0));
        lbl_j2_nom.setText("nomJoueur2");
        panneau_info_partie.add(lbl_j2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        lbl_j2_couleur.setForeground(new java.awt.Color(0, 102, 0));
        lbl_j2_couleur.setText("couleurjoueur2");
        panneau_info_partie.add(lbl_j2_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 102, 0));
        jLabel12.setText("Couleur : ");
        panneau_info_partie.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("Desintegrateurs : ");
        panneau_info_partie.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Infos Joueurs ");
        panneau_info_partie.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setText("Joueur 2 : ");
        panneau_info_partie.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbl_j1_nom1.setForeground(new java.awt.Color(0, 0, 153));
        lbl_j1_nom1.setText("nomJoueur1");
        panneau_info_partie.add(lbl_j1_nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        getContentPane().add(panneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 290, 290));

        btn_col_6.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_6.setText("7");
        btn_col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 60, 40, -1));

        btn_col_0.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_0.setForeground(new java.awt.Color(51, 0, 153));
        btn_col_0.setText("1");
        btn_col_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 40, -1));

        btn_col_1.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_1.setText("2");
        btn_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 60, 40, -1));

        btn_col_2.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_2.setText("3");
        btn_col_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 60, 40, -1));

        btn_col_3.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_3.setText("4");
        btn_col_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 60, 40, -1));

        btn_col_4.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_4.setText("5");
        btn_col_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 60, 40, -1));

        btn_col_5.setBackground(new java.awt.Color(102, 102, 255));
        btn_col_5.setText("6");
        btn_col_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 40, -1));

        setBounds(0, 0, 1057, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur2ActionPerformed

    private void btn_col_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_2ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(2) == true) {
            btn_col_2.setEnabled(false);
        }
        jouerDansColonne(2);
    }//GEN-LAST:event_btn_col_2ActionPerformed

    private void btn_col_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_3ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(3) == true) {
            btn_col_3.setEnabled(false);
        }
        jouerDansColonne(3);
    }//GEN-LAST:event_btn_col_3ActionPerformed

    private void btn_col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_6ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(6) == true) {
            btn_col_6.setEnabled(false);
        }
        jouerDansColonne(6);
    }//GEN-LAST:event_btn_col_6ActionPerformed

    private void btn_col_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_4ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(4) == true) {
            btn_col_4.setEnabled(false);
        }
        jouerDansColonne(4);
    }//GEN-LAST:event_btn_col_4ActionPerformed

    public boolean jouerDansColonne(int indice_colonne) {
        boolean resultatAction;

        resultatAction = grilleDeJeu.ajouterJetonDansColonne(JoueurCourant, indice_colonne);
        panneau_grille.repaint();

        lbl_j1_desint.setText(Listejoueurs[0].nombreDesintegrateurs + "");
        lbl_j2_desint.setText(Listejoueurs[1].nombreDesintegrateurs + "");

        boolean vict_j1 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[0]);
        boolean vict_j2 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[1]);

        if (vict_j1 && !vict_j2) {
            textemessage.setText(" Victoire de  " + Listejoueurs[0].Nom);
        }
        if (vict_j2 && !vict_j1) {
            textemessage.setText(" Victoire de  " + Listejoueurs[1].Nom);
        }

        if (vict_j1 && !vict_j2) {
            if (JoueurCourant == Listejoueurs[0]) {
                textemessage.setText(" Victoire de  " + Listejoueurs[1].Nom + "(faute de jeu de l'autre joueur)");
            } else {
                textemessage.setText(" Victoire de  " + Listejoueurs[0].Nom + "(faute de jeu de l'autre joueur)");
            }

        }
        if (resultatAction == true) {
            return true;
        } else {
            return false;
        }
    }

    public void joueurSuivant() { // permet d'alterner le joueur courant entre le premier et le deuxième joueur
        if (JoueurCourant == Listejoueurs[0]) {
            JoueurCourant = Listejoueurs[1];
        } else {
            JoueurCourant = Listejoueurs[0];
        }
        lbl_jcourant.setText(JoueurCourant.Nom);
    }
    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_info_joueur.setVisible(true);
        panneau_info_partie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint(); // pour rafraîchir l'affichage de la grille de jeu
        btn_start.setEnabled(false); // désactiver le fait que l'on puisse réappuyer sur le bouton (et donc de recréer une nouvelle grille de jeu à chaque fois)


    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_col_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_0ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(0) == true) {
            btn_col_0.setEnabled(false);
        }
        jouerDansColonne(0);
    }//GEN-LAST:event_btn_col_0ActionPerformed

    private void btn_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_1ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(1) == true) {
            btn_col_1.setEnabled(false);
        }
        jouerDansColonne(1);
    }//GEN-LAST:event_btn_col_1ActionPerformed

    private void btn_col_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_5ActionPerformed
        // TODO add your handling code here:
        joueurSuivant();
        if (grilleDeJeu.colonne_remplie(5) == true) {
            btn_col_5.setEnabled(false);
        }
        jouerDansColonne(5);
    }//GEN-LAST:event_btn_col_5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDejeu().setVisible(true);
            }
        });
    }

    void initialiserPartie() {
        //Mise en place de la grille
        grilleDeJeu.viderGrille();

        //Création des joueurs
        String nomJoueur1 = nom_joueur1.getText();
        Joueur J1 = new Joueur(nomJoueur1);

        String nomJoueur2 = nom_joueur2.getText();
        Joueur J2 = new Joueur(nomJoueur2);
        Listejoueurs[0] = J1;
        Listejoueurs[1] = J2;

        attribuerCouleursAuxJoueurs();

        System.out.println(J1.Nom + " est de couleur " + J1.Couleur);
        System.out.println(J2.Nom + " est de couleur " + J2.Couleur);

        lbl_j1_nom1.setText(nomJoueur1);
        lbl_j2_nom.setText(nomJoueur2);

        lbl_j1_couleur.setText(J1.Couleur);
        lbl_j2_couleur.setText(J2.Couleur);

        lbl_j1_desint.setText(J1.nombreDesintegrateurs + "");
        lbl_j2_desint.setText(J2.nombreDesintegrateurs + "");

        // On donne des jetons aux joueurs
        for (int i = 0; i < 21; i++) {

            Jeton J = new Jeton(Listejoueurs[0].Couleur);

            J1.ajouterJeton(J);

            J2.ajouterJeton(new Jeton(J2.Couleur));
        }

        // Determine qui est le premier joueur
        Random r = new Random();
        boolean le_premier = r.nextBoolean();
        if (le_premier) {
            JoueurCourant = Listejoueurs[0];
        } else {
            JoueurCourant = Listejoueurs[1];
        }

        lbl_jcourant.setText(JoueurCourant.Nom);

        // Génération des 5 trous noirs et de 2 désintégrateurs sur les trou noirs
        int compteur = 0;
        for (int i = 0; i < 5; i++) {
            int ligne_trou_noir = r.nextInt(6);
            int colonne_trou_noir = r.nextInt(7);
            if (compteur < 2) {
                if (!grilleDeJeu.placerDesintegrateur(ligne_trou_noir, colonne_trou_noir)) {
                    compteur--;
                }
                compteur = compteur + 1;
            }
            if (!grilleDeJeu.placerTrouNoir(ligne_trou_noir, colonne_trou_noir)) {
                i--;
            }
        }

        // On place les trois derniers désintégrateurs
        for (int i = 0; i < 3; i++) {
            int ligne_désin = r.nextInt(6);
            int colonne_désin = r.nextInt(7);
            if (!grilleDeJeu.placerDesintegrateur(ligne_désin, colonne_désin) || grilleDeJeu.Cellules[ligne_désin][colonne_désin].presenceTrouNoir()) {
                i--;
            }
        }

    }

    void attribuerCouleursAuxJoueurs() {
        Random r = new Random();
        boolean couleur;
        couleur = r.nextBoolean();
        if (couleur) {
            Listejoueurs[0].Couleur = "Rouge";
            Listejoueurs[1].Couleur = "Jaune";
        } else {
            Listejoueurs[0].Couleur = "Jaune";
            Listejoueurs[1].Couleur = "Rouge";
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_j1_couleur;
    private javax.swing.JLabel lbl_j1_desint;
    private javax.swing.JLabel lbl_j1_nom1;
    private javax.swing.JLabel lbl_j2_couleur;
    private javax.swing.JLabel lbl_j2_desint;
    private javax.swing.JLabel lbl_j2_nom;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info_joueur;
    private javax.swing.JPanel panneau_info_partie;
    private javax.swing.JTextArea textemessage;
    // End of variables declaration//GEN-END:variables
}
